### ISSUE TITLE
Not working for AAC IceCast streams

### ISSUE THREAD

**Issue by MarshmelloSUCKS** [Freeedle/Essential-Audio-Player#1]
I run an IceCast stream and would like to use Essential Audio Player instead of the native HTML5 player. However, when I set it up and press play, it just loads. With the console open, I get the following:
```HEAD https://ice1.msx.gay:8443/kmsx.aac?random=927 [HTTP/1.0 400 Bad Request 124ms]```
Below is the embed code for the player:
```<div class="essential_audio" data-url="https://ice1.msx.gay:8443/kmsx.aac">Looks like your browser doesn't support the player. Use the link below to play in your own player.</div>```
`essential_audio.css` and `essential_audio.js` are linked to in the head of the page. The page is [here](https://ice1.msx.gay/test.html) if you want to take a look for yourself.

**Comment by Freeedle** [comment]
Hey there,

thanks for being interested in my little player!
Indeed, it doesn’t work with your link…
Let me take a quick look at the problem, and I get back to you!

Greetings,

Freedle

**Comment by Freeedle** [comment]
The answer is:
The way the script requests audio files is failing with streams.
This is indeed a weak spot in the player, but fixing it would mean to rewrite the entire code.
Perhaps in a future release...
Sorry for now.

**Comment by Freeedle** [comment]
Hm, big problem.

The way the script requests audio files is failing with streams.
I’m aware that this is a weak spot in my little player, but fixing this
would mean to rewrite the entire code.
Perhaps in a future release...
Sorry for now.

But I’m very sure that there’s another player out there that will work for
you!

Greetings,

Freedle
