### ISSUE TITLE
Add a package.json and publish on npm

### ISSUE THREAD

**Issue by GregOriol** [Freeedle/Essential-Audio-Player#2]
That way it would be more modern and easier to integrate in a project!

**Comment by Freeedle** [comment]
Nice proposal. Alas, I’m not a real programmer and have no clue of what you’re talking about. Perhaps some day I’ll find out...

**Comment by GregOriol** [comment]
This is not very reassuring about the code of the component you know? :-)

**Comment by Freeedle** [comment]
Hey, don’t say that in public!

**Comment by pedropcamellon** [comment]
Hi! Any update on this? I want to help

**Comment by Freeedle** [comment]
Hi there!
No update on this so far. I have no clue of npm, just happily tinkered together the audio player. If you want to help, always welcome!

**Comment by pedropcamellon** [comment]
I think this would be helpful. [ref
](https://docs.npmjs.com/creating-and-publishing-scoped-public-packages#publishing-scoped-public-packages)

**Comment by Freeedle** [comment]
er, yes, certainly...

**Comment by pedropcamellon** [comment]
...?? I can go with you step by step 🤷🏻‍♂️

**Comment by pedropcamellon** [comment]
Please follow the link provided. Sign up for a new account in npmjs.com.

**Comment by Freeedle** [comment]
No, OSX.

**Comment by pedropcamellon** [comment]
Following "https://docs.npmjs.com/creating-and-publishing-unscoped-public-packages":

1. On the command line, create a directory for your package:
mkdir my-test-package (DONE: you already have a folder with your project)

2. Navigate to the root directory of your package:
cd my-test-package (Open a cmd, powershell, shell in your project dir)

3. If you are using git to manage your package code, in the package root directory, run the following commands, replacing git-remote-url with the git remote URL for your package:
git init (DONE: you already have a repo)
git remote add origin https://github.com/Freeedle/Essential-Audio-Player.git (DONE: you already have your repo in github.com)

4. In the package (github project) root directory (in your pc), run the `npm init`:
```
D:\Documents\GitHub\Essential-Audio-Player> npm init                                                                                         package name: (Essential-Audio-Player)                                                                                                          version: (1.0.0)                                                                                                                                                                                                                                            
description: ...
entry point: ./Essential_Audio_Player_v1.0.3/essential_audio.js       // we have to check if this works
test command:
git repository: (https://github.com/Freeedle/Essential-Audio-Player.git)
keywords:
author:
license: (ISC)

About to write to D:\Documents\GitHub\Essential-Audio-Player\package.json:
{
  "name": "test",
  "version": "1.0.0",
  "description": "__your readme.md content will appear here__",
  "main": "./Essential_Audio_Player_v1.0.3/essential_audio.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Freeedle/Essential-Audio-Player.git"
  },
  "author": "Freeedle",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/Freeedle/Essential-Audio-Player/issues"
  },
  "homepage": "https://github.com/Freeedle/Essential-Audio-Player#readme"
}
```

5. Test your package

They say:
```
To test your package, run npm install with the full path to your package directory:
npm install path/to/my-package

(It's not working for me)
```

Run isntead: `D:\Documents\GitHub\Essential-Audio-Player> npm link` and you should get something like this:
```
npm link
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

added 1 package, and audited 3 packages in 591ms

found 0 vulnerabilities
```

6. Add a user.
Run `npm adduser`:
```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN adduser `adduser` will be split into `login` and `register` in a future version. `adduser` will become an alias of `register`. `login` (currently an alias) will become its own command.
npm notice Log in on https://registry.npmjs.org/
Username: your-user
Password: your-pwd
Email: (this IS public)
Email: (this IS public) your@oooo.com
npm notice Please check your email for a one-time password (OTP)
Enter one-time password: 909090990
Logged in as your-user on https://registry.npmjs.org/.

8. Publish it running `npm publish` you should get something like this:
```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm notice
npm notice package: ppcqtest@1.0.0
npm notice === Tarball Contents ===
npm notice 11B  README.md
npm notice 481B package.json
npm notice 0B   ./Essential_Audio_Player_v1.0.3/essential_audio.js
npm notice === Tarball Details ===
npm notice name:          Essential_Audio_Player_v1.0.3
npm notice version:       1.0.0
npm notice filename:      Essential_Audio_Player_v1.0.3-1.0.0.tgz
npm notice package size:  387 B
npm notice unpacked size: 492 B
npm notice shasum:        jsjsjsjsjsjsj8282828jaja
npm notice integrity:     sha512-9ad9aw9a9dddjdjd
npm notice total files:   3
npm notice
npm notice Publishing to https://registry.npmjs.org/
+ Essential_Audio_Player_v1.0.3@1.0.0
```

10. To see your public package page, visit

"https://npmjs.com/package/Essential_Audio_Player_v1.0.3"

Public packages will say public below the package name on the npm website.

******
I think that's it!

**Comment by pedropcamellon** [comment]
I think we should work on the naming convention and general project folder and files structure. We should change the package name from `Essential_Audio_Player_v1.0.3` to essential_Audio_Player

**Comment by Freeedle** [comment]
Ok, I read all that on the npm instructions page. But still, I get stuck in the beginning:
Under 2., what is "Open a cmd, powershell, shell in your project dir"???
And then:
"3. If you are using git to manage your package code..." - I don't use git. What is git? I have a GitHub account, but I assume this is not using git. Or is it?
And then, running an npm init: Do I need to install anything on my computer? How does my system know what an npm init ist?

**Comment by Freeedle** [comment]
Removing the "v1.0.3" is rather easy...

**Comment by pedropcamellon** [comment]
1. "Open a cmd, powershell, shell in your project dir":
- On your Mac, do one of the following: Click the Launchpad icon in the Dock, type Terminal in the search field, then click Terminal. In the Finder , open the /Applications/Utilities folder, then double-click Terminal.

2.  "I have a GitHub account, but I assume this is not using git. Or is it?"
- It's not. Go to your account, then your project, and click on Code btn:
![image](https://user-images.githubusercontent.com/83567517/195340815-6fe36a81-db22-49f3-bd82-86a1eabb7334.png)

Then click on Open on Github desktop (the easiest way of working with git):
![image](https://user-images.githubusercontent.com/83567517/195341033-85a19693-b687-456f-8130-6ecd74164c18.png)

How do you uploaded your repo?

**Comment by pedropcamellon** [comment]
I see now:
![image](https://user-images.githubusercontent.com/83567517/195341503-cc5945f8-864f-4578-b912-9dd7f7e52690.png)

You uploaded your files directly. Do you?

**Comment by pedropcamellon** [comment]
- "Do I need that?" You dont, but it is a lot easier!
- "But couldn’t I use the GitHub URL under Code/Clone/HTTPS for the npm package directly?" You are missing some steps from above:

"If you are using git to manage your package code, in the package root directory, run the following commands, replacing git-remote-url with the git remote URL for your package:
- git init ( ___ DONE: you already have a repo  ___ Sorry! You have not.  Here  GitHub Desktop will help you )
- git remote add origin https://github.com/Freeedle/Essential-Audio-Player.git 
( ___ DONE: you already have your repo in github.com ___  Dont do this. Go to your github account / repositories, and open the repo with GitHub Desktop. It will download all the project and will help you init the repo)

In the package (github project) root directory (in your pc), run the npm init
```

**Comment by Freeedle** [comment]
Ok, ok...
But back to the beginning:
I know how to open the terminal, but still I do not understand "Open a cmd, powershell, shell in your project dir".
cmd? powershell? shell? either one? Or all three of them? Simultaneously? Subsequently? What? How?

**Comment by pedropcamellon** [comment]
Haha! One of them.

**Comment by Freeedle** [comment]
Which one then?

**Comment by pedropcamellon** [comment]
Shells are for running commands like `>> git init`. You are not going to do that. Instead:
- Go to your github account / repositories, and open the repo with GitHub Desktop. It will download all the project and will help you init the repo.

From above:

2.  "I have a GitHub account, but I assume this is not using git. Or is it?"
- Not your account, but Github Desktop. Go to your account, then your project, and click on Code btn:
![image](https://user-images.githubusercontent.com/83567517/195340815-6fe36a81-db22-49f3-bd82-86a1eabb7334.png)

Then click on Open on Github desktop (the easiest way of working with git):
![image](https://user-images.githubusercontent.com/83567517/195341033-85a19693-b687-456f-8130-6ecd74164c18.png)

**Comment by Freeedle** [comment]
Installed GitHub Desktop now. More confusion. I have cloned the repository back to my computer. Actually pointless: I already have the files on my computer - that’s their original origin.
Anyway, I see it doesn't make sense to put the entire repository to npm as it contains useless additional files. So, we just want the folder "Essential_Audio_Player_v1.0.3", right? I can make a copy of my original folder and just name it "Essential_Audio_Player", for example. No need of GitHub Desktop for that. Right?
With GitHub Desktop or without it – what next?

**Comment by Freeedle** [comment]
Another important general question: If I get it right, npm is like a JavaScript database. The Essential Audio Player consists of two essential files: the JS file, but also the CSS file which is not just for decoration but which contains important functional stylings. Will this work with npm anyway?

**Comment by pedropcamellon** [comment]
You NEED a git repo on your Mac, so you NEED Github Desktop (shell is not an option right now).

1. You can extract all files from "Essential_Audio_Player" folder to the root folder. 
2. Rename "essential_audio.js" to index.js (default). 
3. Move "Essential-Audio-Player/Essential_Audio_Player_v1.0.3/sample.htm" to "Essential-Audio-Player/examples/index.htm" (we will have to modify later index.html file for it to keep working).

- "npm is like a JavaScript database. The Essential Audio Player consists of two essential files: the JS file, but also the CSS file which is not just for decoration but which contains important functional stylings. Will this work with npm anyway?"

Yes. For example, Bootstrap has an NPM package with their CSS in it.
https://www.npmjs.com/package/bootstrap
https://github.com/twbs/bootstrap

**Comment by Freeedle** [comment]
Tried to run git init and also npm init, just to see what happens. Terminal says "command not found".
I already installed the additional developer package to the system, so it's not coming from there. This means, I have to install something else to make my terminal understand the commands. I don’t know what to install. It’s all super complicated, I have no idea where to begin...

**Comment by pedropcamellon** [comment]
"additional developer package to the system" which one?
Did you installed github desktop?

**Comment by Freeedle** [comment]
So, after some fiddling, here's the news:
- no GitHub Desktop is needed. You can do it with any folder on your computer.
- I had to install node.js in order to get the npm command working (installed it directly, without homebrew)
- the additional developer package to the system was something with xcode, I didn’t pay much attention (don't even remember if it was necessary anyway)...
- ultimately, I successfully managed to publish my package on npm
- but alas, I messed up some details and had to delete the whole package again (republishing the same version appears to be forbidden)
- now I have to wait 24 hours to be allowed to republish the package
- so, no npm package today, but tomorrow!
- and thanks for nudging me into getting this problem solved!

**Comment by pedropcamellon** [comment]
You're welcome!

**Comment by Freeedle** [comment]
Done.
