### ISSUE TITLE
Chrome Console error "Uncaught (in promise)" after clicking on play

### ISSUE THREAD

**Issue by Mesign** [Freeedle/Essential-Audio-Player#4]
I noticed that the audioplayer on the [website](https://tinyurl.com/dcdmytjc) sometimes does not work. When checking for errors I see the following in Google Chome (90.0.4430.212) Console after pressing on the play button:
`Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22`

It is weird that the audioplayer sometime does work and sometime does not work. On the moment of writing this it works again(?).

Any idea what could cause this?

**Comment by Freeedle** [comment]
The error alert you’re mentioning has been dealt with in issue #3 already, and this is certainly not the reason why the player would not be working (please look into issue #3 for more info).
The only thing I noticed so far that can make the audio player stumble is slow server response. This may cause the player to get lost.
The Essential Audio Player’s official website itself is hosted with PCextreme (in the Netherlands), and by moments their servers appear to be stuck, which causes problems with the player (super annoying for the website). Do you, by any chance, use PCextreme? They are the issue!

**Comment by Mesign** [comment]
Oke, thank you. I look into it and will I talk to the host (not PCextreme).

**Comment by Freeedle** [comment]
Good news: the problem is resolved!
Works without throwing errors in the newly released Version 2.0
