### ISSUE TITLE
Accessibility player

### ISSUE THREAD

**Issue by Mesign** [Freeedle/Essential-Audio-Player#5]
Is there a easy way to make the player accessible with tab and enter? 

I'm using multiple players with no ID's on a page but can't acces them with keyboard.

**Comment by Freeedle** [comment]
Hum. This is actually not a player issue.
Instead, it requires additional programming. You might add the tabindex attribute to the player DIVs, and then it would perhaps take some additional JavaScript programming to catch the player's tab selection and the enter key action. You might highlight the tab selection with additional CSS of your own taste and style...
Be aware that even if you don't specify IDs, each player DIV will get a simple ID number assigned by the script (starting with 1). You might want to work with IDs (specific or automatically assigned) in your additional programming.
Just some hints. Are they helpful?

**Comment by Mesign** [comment]
Thank you for the hints. Going to try what you suggested.
