### ISSUE TITLE
Audio stopped playing after upgrading to v2.0.

### ISSUE THREAD

**Issue by yrammos** [Freeedle/Essential-Audio-Player#7]
Firefox Developer Edition reports the following:

```
 Load of media resource https://<REDACTED> failed. 
All candidate resources failed to load. Media load paused.
Cannot play media. No decoders for requested formats: audio/e-1
```

Apart from updating the essential audio script. No other changes were made to my website.

Thanks.

**Comment by Freeedle** [comment]
Did you take notice of the changed handling of multiple files?
Now as a comma separated list of entire URLs.

**Comment by yrammos** [comment]
Yes I did — but I don’t think this change is relevant to my case, as I only have a single URL linked, and it is indeed full (`https://.….`).

**Comment by yrammos** [comment]
SOLVED: I needed to append the audio file extension to the URL (in this sense, the URL was indeed not "complete"). With the previous version of the library, the extension was not necessary. 

This issue may closed as far as I’m concerned — thank you.

**Comment by Freeedle** [comment]
Great.
The explanation: The 2.0 script now extracts the file extension from the URL. Known audio file extensions are translated into the correct MIME type (".mp3" becomes "audio/mpeg", for example). Unknown file extensions are used directly as MIME type (".unknown" becomes "audio/unknown"). Somehow the script extracted ".e-1" from your URL...
